= Download and API Reference
:page-topic-type: concept

[abstract]
All production-ready Couchbase Spark connector artifacts are downloadable through Maven Central.
Prerelease versions are available through our Couchbase Maven repository for easy consumption.

== Current Release 3.0.0

The connector is currently compiled against Scala 2.12 to comply with Spark 3.1.
Here is the coordinate for the artifact:

* *GroupId:* com.couchbase.client
* *ArtifactId:* spark-connector_2.12
* *Version:* 3.1.0

If you are using Scala, here is the snippet you can use:

[source,scala]
----
libraryDependencies += "com.couchbase.client" %% "spark-connector" % "3.1.0"
----

This can also be used in a Java application and imported with Maven or Gradle.

It can also be downloaded manually here: http://packages.couchbase.com/clients/connectors/spark/3.0.0/Couchbase-Spark-Connector_2.12-3.1.0.zip[Download (Scala 2.12 / Java)^] | http://docs.couchbase.com/sdk-api/couchbase-spark-connector-3.1.0/[API Reference^]

Note that the download contains an assembled jar, which means they contain all the dependencies in one "fat jar".
This means that you don't need to juggle multiple dependencies if you want to use the jar as part of Spark's command line access tools (like the shell) or add it to the classpath of workers.

If you want to run a prerelease version, they are available from our Couchbase Repository instead of Maven Central:

[source,scala]
----
resolvers += "Couchbase Repository" at "http://files.couchbase.com/maven2/"
----