= Java API
:page-topic-type: concept

[abstract]
In addition to the Scala API, some APIs can also be accessed from Java.

== Creating a Spark Session

When accessing Spark from java, a `SparkSession` needs to be created, similar to this:

[source,java]
----
include::example$JavaApi.java[tag=context,indent=0]
----

Properties and configuration are set in the same way.

== Using SparkSQL DataFrames

The `DataFrame` APIs can be accessed very similarly from Java compared to Scala.

[source,java]
----
include::example$JavaApi.java[tag=dfread,indent=0]
----

Note that since later version of Spark 2, a `DataFrame` is just an alias for a `Dataset<Row>` and can be interacted with in the same way.

If executed against the `travel-sample` bucket, this will print:

[source]
----
+-------------+--------+-------------+----+----+-----+-----------+-------+
|    __META_ID|callsign|      country|iata|icao|   id|       name|   type|
+-------------+--------+-------------+----+----+-----+-----------+-------+
|   airline_10|MILE-AIR|United States|  Q5| MLA|   10|40-Mile Air|airline|
|airline_10123|     TXW|United States|  TQ| TXW|10123|Texas Wings|airline|
|airline_10226|  atifly|United States|  A1| A1F|10226|     Atifly|airline|
+-------------+--------+-------------+----+----+-----+-----------+-------+
----

Please see the corresponding scala sections for `DataFrame` on how to configure the data source and which properties can be applied.

== Using SparkSQL Datasets

Since Datasets work with actual Java objects, first create one:

[source,java]
----
include::example$JavaApi.java[tag=airportclass,indent=0]
----

Next, you can convert a `DataFrame` to a `Dataset` through the `.as()` API:

[source,java]
----
include::example$JavaApi.java[tag=dsread,indent=0]
----

This will print:

[source]
----
Airline:Airline{name='40-Mile Air', callsign='MILE-AIR', country='United States'}
Airline:Airline{name='Texas Wings', callsign='TXW', country='United States'}
Airline:Airline{name='Atifly', callsign='atifly', country='United States'}
----

== RDD Access

Raw RDD access from the Java API is currently not available, please use the higher level DataFrame and Dataset APIs.