= Release Notes
:page-topic-type: concept

[abstract]
Release notes for the Spark Connector.

== Couchbase Spark Connector 3.1.0 GA (September 2021)

Version 3.1.0 is the first version to support Spark 3.1.x and is built on top of the Couchbase Scala SDK 1.1.x.

This release contains identical features to the Spark 3.0.0 connector, the only difference being compiled against Spark 3.1.x. Please refer to the 3.0 migration guide for changes and new features over 2.4.x.

*Highlights*

* Support for Apache Spark 3.1.x

== Couchbase Spark Connector 3.0.0 GA (September 2021)

Version 3.0.0 is the first version to support Spark 3.0.x and is built on top of the Couchbase Scala SDK 1.1.x.

Please note that this release does not have separate release notes, rather refer to the migration guide page for more information.

*Highlights*

* Support for Apache Spark 3.0.x
* Built on top of the new Scala SDK 1.2.x
* Support for Couchbase Server 7.0 and later

== Couchbase Spark Connector 2.4.1 GA (November 2020)

Version 2.4.1 brings support for Couchbase Cloud as well as:

*Features*

* https://issues.couchbase.com/browse/SPARKC-110[SPARKC-110^]: Allow passthrough of timestampFormat and dateFormat for inferring schema
* Updated the Java SDK to 2.7.18
* Allows enabling DNS SRV via a configuration property

*Bug fixes and stability*

* https://issues.couchbase.com/browse/SPARKC-104[SPARKC-104^]: Stopping and restarting of Spark-Couchbase-Streaming-job throws ClassCastException
* Properly propagate the expiry into the `DefaultSource`

== Couchbase Spark Connector 2.4.0 GA (July 2019)

Version 2.4.0 brings support for Spark 2.4.0, and is compiled exclusively with Scala 2.12.

== Couchbase Spark Connector 2.3.0 GA (May 2019)

Version 2.3.0 brings support for Spark 2.3.0 along with:

*Features*

* https://issues.couchbase.com/browse/SPARKC-93[SPARKC-93^]: Support for Apache Spark 2.3.0
* https://issues.couchbase.com/browse/SPARKC-89[SPARKC-89^]: Support Analytics
* https://issues.couchbase.com/browse/SPARKC-88[SPARKC-88^]: Allow N1QL queries to run on Spark node(s) co-located with query service
* https://issues.couchbase.com/browse/SPARKC-96[SPARKC-96^]:
Provide more fault-tolerant batch mutations.
`saveToCouchbase` now takes a `maxConcurrent` parameter, giving the application control over the size of batches that will be written, from each executor.

*Bug fixes and stability*

* https://issues.couchbase.com/browse/SPARKC-85[SPARCK-85^]: Raise N1QL errors as exceptions rather than logging them.
* https://issues.couchbase.com/browse/SPARKC-82[SPARKC-82^]:
When running a N1QLQuery, if multiple buckets have been specified, then the bucket to use must now be explicitly chosen.
E.g. `sc.couchbaseQuery(query, bucketName = "default")`.  This is safer than choosing an arbitrary bucket.
* https://issues.couchbase.com/browse/SPARKC-95[SPARKC-95^]: Fix to get streaming source working with Spark 2.3

== Couchbase Spark Connector 2.2.0 GA (September 2017)

Version 2.2.0 is the first stable release of the 2.2.x series.
It brings support for Spark 2.2 and the following enhancements and bugfixes:

*Spark Core*

* Support for Apache Spark 2.2.0
* https://issues.couchbase.com/browse/SPARKC-80[SPARKC-80^]: Support for Couchbase Server 5.0 and Role-Based Access Control
* https://issues.couchbase.com/browse/SPARKC-77[SPARKC-77^]: Global and per-operation timeout configuration is now possible
* https://issues.couchbase.com/browse/SPARKC-44[SPARKC-44^]: Support for Subdocument Mutations has been added.
* https://issues.couchbase.com/browse/SPARKC-79[SPARKC-79^]: Support for easier SSL/TLS configuration via spark config.

*Spark SQL*

* https://issues.couchbase.com/browse/SPARKC-77[SPARKC-77^]: per-operation timeout configuration is now possible

*Spark Streaming*

No changes for Spark Streaming have been made in this release.


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
